name: automerge
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, edited, unlocked]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
    status: success
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: "pascalgn/automerge-action@v0.8.4"
        env:
          GITHUB_TOKEN: "${{ secrets.ACTIONS }}"
          MERGE_LABELS: "Ready to merge,!in progress!,!blocked, !netlify-cms/draft, !netlify-cms/pending_review, !question, !duplicate, !DO NOT MERGE, !invalid"
          MERGE_REMOVE_LABELS: Ready to merge
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: 3
          MERGE_RETRY_SLEEP: 10000
          UPDATE_LABELS: "Ready to merge,!in progress!,!blocked"
          UPDATE_METHOD: rebase
